version: "3.8"

services:

  web:
    build:
      context: .
      target: prod
    restart: always
    environment:
      - PUID=1000
      - PGID=1000
      - TZ=Europe/Zurich
      - URL=medicalswitzerland.com
      - VALIDATION=http
      - ONLY_SUBDOMAINS=false
      - STAGING=true
    volumes:
      - './nginx/staging.conf:/config/nginx/site-confs/default.conf'
    ports:
      - "80:80"
      - "443:443"
